name: taluxi
description: Taluxi project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  network_communication:
    git:
      url: https://github.com/NonymousMorlock/taluxi_network_communication.git
      ref: main
  provider: ^6.1.2
  real_time_location:
    git:
      url: https://github.com/NonymousMorlock/taluxi_real_time_location.git
      ref: main
  taluxi_common:
    git:
      url: https://github.com/NonymousMorlock/taluxi_common.git
  user_manager:
    git:
      url: https://github.com/NonymousMorlock/taluxi_user_manager.git
      ref: main

dependency_overrides:
  iris_method_channel:
    git:
      url: https://github.com/AgoraIO-Extensions/iris_method_channel_flutter.git
      ref: littlegnal/android-github-runner-linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

flutter:

  assets:
    - assets/images/
    - assets/audio/

  uses-material-design: true

  fonts:
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Bold.ttf
        - asset: assets/fonts/LobsterTwo-Regular.ttf
          style: normal
    - family: PatuaOne
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  
