name: Android-apk-build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🤖 Android Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Set up environment variables
        run: |
          echo "AGORA_APP_ID=${{ secrets.agoraAppId }}" >> $GITHUB_ENV
          echo "ONESIGNAL_APP_ID=${{ secrets.oneSignalAppId }}" >> $GITHUB_ENV
        shell: bash

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: | 
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-


      - run: flutter pub get

      - run: flutter build apk --release --dart-define=AGORA_APP_ID=$AGORA_APP_ID --dart-define=ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID

      - name: Zip output
        run: Compress-Archive -Path build/app/outputs/flutter-apk/app-release.apk -DestinationPath FlutterApkExport.zip
        shell: powershell

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterApkExport.zip
          tag: v1.0
          overwrite: true
          body: "This is the first Android release"
